export const MutationTypes = {
  SET_HORSES: 'SET_HORSES',
  SET_ROUNDS: 'SET_ROUNDS',
  SET_STATUS: 'SET_STATUS',
  SET_CURRENT_ROUND_INDEX: 'SET_CURRENT_ROUND_INDEX',
  SET_RACE_PROGRESS: 'SET_RACE_PROGRESS',
  UPDATE_HORSE_PROGRESS: 'UPDATE_HORSE_PROGRESS',
  COMPLETE_ROUND: 'COMPLETE_ROUND',
  ADVANCE_TO_NEXT_ROUND: 'ADVANCE_TO_NEXT_ROUND',
} as const

export const ActionTypes = {
  GENERATE_PROGRAM: 'generateProgram',
  START_PAUSE: 'startPause',
  RUN_CURRENT_ROUND: 'runCurrentRound',
  FINISH_ROUND: 'finishRound',
} as const
